"""
config.py

Central configuration for the Agentic Question Paper Generator.
All settings are loaded from environment variables (via .env file).
No hardcoded secrets or paths anywhere else in the codebase.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Project Root
# ---------------------------------------------------------------------------
BASE_DIR: Path = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Load environment files
# ---------------------------------------------------------------------------
load_dotenv(BASE_DIR / ".env")
load_dotenv(BASE_DIR / "env")


# ---------------------------------------------------------------------------
# Groq LLM Configuration
# ---------------------------------------------------------------------------
class LLMConfig:
    GROQ_API_KEY: str = os.getenv("GROQ_API_KEY", "")
    MODEL_NAME: str = os.getenv("MODEL_NAME", "llama-3.3-70b-versatile")

    # Generation settings
    TEMPERATURE: float = float(os.getenv("TEMPERATURE", "0.3"))

    # Retry settings for Groq API calls
    MAX_RETRIES: int = int(os.getenv("MAX_RETRIES", "3"))
    RETRY_DELAY_SECONDS: float = float(os.getenv("RETRY_DELAY_SECONDS", "2.0"))

    @classmethod
    def validate(cls) -> None:
        """Raise if critical LLM config is missing."""
        if not cls.GROQ_API_KEY:
            raise EnvironmentError(
                "GROQ_API_KEY is not set. "
                "Please add it to your .env file."
            )


# ---------------------------------------------------------------------------
# File System Paths
# ---------------------------------------------------------------------------
class PathConfig:
    BASE_DIR: Path = BASE_DIR
    UPLOADED_DOCUMENTS_DIR: Path = BASE_DIR / "uploaded_documents"
    GENERATED_PAPERS_DIR: Path = BASE_DIR / "generated_papers"
    LOGS_DIR: Path = BASE_DIR / "logs"

    @classmethod
    def ensure_directories(cls) -> None:
        """Create all required directories if they don't exist."""
        for directory in [
            cls.UPLOADED_DOCUMENTS_DIR,
            cls.GENERATED_PAPERS_DIR,
            cls.LOGS_DIR,
        ]:
            directory.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------------------------
class LogConfig:
    LOG_LEVEL: str = os.getenv("LOG_LEVEL", "INFO")
    LOG_FILE: Path = PathConfig.LOGS_DIR / "application.log"
    LOG_FORMAT: str = (
        "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"
    )
    DATE_FORMAT: str = "%Y-%m-%d %H:%M:%S"
    # Max log file size before rotation (10 MB)
    MAX_BYTES: int = 10 * 1024 * 1024
    BACKUP_COUNT: int = 5


# ---------------------------------------------------------------------------
# FastAPI Configuration
# ---------------------------------------------------------------------------
class APIConfig:
    HOST: str = os.getenv("API_HOST", "0.0.0.0")
    PORT: int = int(os.getenv("API_PORT", "8000"))
    DEBUG: bool = os.getenv("DEBUG", "false").lower() == "true"
    TITLE: str = "Agentic AI Question Paper Generator"
    DESCRIPTION: str = (
        "Multi-Agent AI system that generates university question papers "
        "from uploaded syllabus documents using LangGraph and Groq LLM."
    )
    VERSION: str = "1.0.0"

    # File upload limits (RAG accepts larger syllabus PDFs than the old 10 MB cap)
    MAX_UPLOAD_SIZE_MB: int = int(os.getenv("MAX_UPLOAD_SIZE_MB", "50"))
    ALLOWED_EXTENSIONS: list[str] = ["pdf", "txt", "docx"]


# ---------------------------------------------------------------------------
# PDF Generation Configuration
# ---------------------------------------------------------------------------
class PDFConfig:
    # Paper size: A4 (points: 595 x 842)
    PAGE_WIDTH: float = 595.0
    PAGE_HEIGHT: float = 842.0

    # Margins in points (1 inch = 72 points)
    MARGIN_LEFT: float = 72.0
    MARGIN_RIGHT: float = 72.0
    MARGIN_TOP: float = 72.0
    MARGIN_BOTTOM: float = 72.0

    # Fonts
    FONT_HEADER: str = "Helvetica-Bold"
    FONT_BODY: str = "Helvetica"
    FONT_SIZE_TITLE: int = 14
    FONT_SIZE_HEADER: int = 11
    FONT_SIZE_BODY: int = 10
    FONT_SIZE_FOOTER: int = 8

    # Footer text
    FOOTER_TEXT: str = "Generated by Agentic AI Question Paper Generator"


# ---------------------------------------------------------------------------
# Aggregated Settings (single import point for rest of codebase)
# ---------------------------------------------------------------------------
class Settings:
    llm = LLMConfig
    paths = PathConfig
    log = LogConfig
    api = APIConfig
    pdf = PDFConfig

    @classmethod
    def initialize(cls) -> None:
        """
        Run all startup checks and directory creation.
        Call once at application startup in main.py.
        """
        cls.paths.ensure_directories()
        cls.llm.validate()


# Singleton-style export
settings = Settings()
